export type Amulets =
  | "Coral Amulet"
  | "Paua Amulet"
  | "Amber Amulet"
  | "Jade Amulet"
  | "Lapis Amulet"
  | "Gold Amulet"
  | "Agate Amulet"
  | "Citrine Amulet"
  | "Turquoise Amulet"
  | "Onyx Amulet"
  | "Marble Amulet"
  | "Blue Pearl Amulet"
  | "Unset Amulet"
  | "Seaglass Amulet"
  | "Ruby Amulet"
  | "Ashscale Talisman"
  | "Black Maw Talisman"
  | "Breakrib Talisman"
  | "Chrysalis Talisman"
  | "Deadhand Talisman"
  | "Deep One Talisman"
  | "Lone Antler Talisman"
  | "Mandible Talisman"
  | "Rot Head Talisman"
  | "Undying Flesh Talisman"
  | "Writhing Talisman"
  | "Avian Twins Talisman"
  | "Clutching Talisman"
  | "Fangjaw Talisman"
  | "Hexclaw Talisman"
  | "Horned Talisman"
  | "Primal Skull Talisman"
  | "Splitnewt Talisman"
  | "Wereclaw Talisman"
  | "Longtooth Talisman"
  | "Monkey Paw Talisman"
  | "Monkey Twins Talisman"
  | "Rotfeather Talisman"
  | "Spinefuse Talisman"
  | "Three Hands Talisman"
  | "Three Rat Talisman"
  | "Greatwolf Talisman"
  | "Bonespire Talisman"
  | "Astrolabe Amulet"
  | "Simplex Amulet"
  | "Focused Amulet"
  | (string & {})
