export type DelveStackableSocketableCurrency =
  | "Primitive Alchemical Resonator"
  | "Potent Alchemical Resonator"
  | "Powerful Alchemical Resonator"
  | "Prime Alchemical Resonator"
  | "Primitive Chaotic Resonator"
  | "Potent Chaotic Resonator"
  | "Powerful Chaotic Resonator"
  | "Prime Chaotic Resonator"
  | (string & {})
