export type HeistTools =
  | "Simple Lockpick"
  | "Standard Lockpick"
  | "Fine Lockpick"
  | "Master Lockpick"
  | "Leather Bracers"
  | "Studded Bracers"
  | "Runed Bracers"
  | "Steel Bracers"
  | "Crude Sensing Charm"
  | "Fine Sensing Charm"
  | "Polished Sensing Charm"
  | "Thaumaturgical Sensing Charm"
  | "Voltaxic Flashpowder"
  | "Trarthan Flashpowder"
  | "Azurite Flashpowder"
  | "Thaumetic Flashpowder"
  | "Crude Ward"
  | "Lustrous Ward"
  | "Shining Ward"
  | "Thaumaturgical Ward"
  | "Essential Keyring"
  | "Versatile Keyring"
  | "Skeleton Keyring"
  | "Grandmaster Keyring"
  | "Eelskin Sole"
  | "Foxhide Sole"
  | "Winged Sole"
  | "Silkweave Sole"
  | "Basic Disguise Kit"
  | "Theatre Disguise Kit"
  | "Espionage Disguise Kit"
  | "Regicide Disguise Kit"
  | "Steel Drill"
  | "Flanged Drill"
  | "Sulphur Blowtorch"
  | "Thaumetic Blowtorch"
  | (string & {})
