export type Incubators =
  | "Whispering Incubator"
  | "Singular Incubator"
  | "Cartographer's Incubator"
  | "Otherworldly Incubator"
  | "Abyssal Incubator"
  | "Fragmented Incubator"
  | "Skittering Incubator"
  | "Infused Incubator"
  | "Fossilised Incubator"
  | "Diviner's Incubator"
  | "Primal Incubator"
  | "Geomancer's Incubator"
  | "Ornate Incubator"
  | "Celestial Armoursmith's Incubator"
  | "Celestial Blacksmith's Incubator"
  | "Celestial Jeweller's Incubator"
  | "Obscured Incubator"
  | "Foreboding Incubator"
  | "Thaumaturge's Incubator"
  | "Mysterious Incubator"
  | "Blighted Incubator"
  | "Maddening Incubator"
  | "Kalguuran Incubator"
  | "Fine Incubator"
  | (string & {})
