export type ItemClasses =
  | "Stackable Currency"
  | "One Hand Axes"
  | "Two Hand Axes"
  | "Bows"
  | "Claws"
  | "Daggers"
  | "Rune Daggers"
  | "One Hand Maces"
  | "Sceptres"
  | "Two Hand Maces"
  | "Staves"
  | "Warstaves"
  | "One Hand Swords"
  | "Thrusting One Hand Swords"
  | "Two Hand Swords"
  | "Wands"
  | "Fishing Rods"
  | "Body Armours"
  | "Boots"
  | "Gloves"
  | "Helmets"
  | "Shields"
  | "Amulets"
  | "Belts"
  | "Quivers"
  | "Rings"
  | "Jewels"
  | "Divination Cards"
  | "Life Flasks"
  | "Mana Flasks"
  | "Hybrid Flasks"
  | "Utility Flasks"
  | "Skill Gems"
  | "Support Gems"
  | "Map Fragments"
  | "Vault Keys"
  | "Quest Items"
  | "Labyrinth Items"
  | "Labyrinth Trinkets"
  | "Breachstones"
  | "Pieces"
  | "Abyss Jewels"
  | "Maps"
  | "Incursion Items"
  | "Delve Stackable Socketable Currency"
  | "Incubators"
  | "Trinkets"
  | "Heist Targets"
  | "Contracts"
  | "Blueprints"
  | "Heist Cloaks"
  | "Heist Brooches"
  | "Heist Tools"
  | "Heist Gear"
  | "Misc Map Items"
  | "Expedition Logbooks"
  | "Atlas Upgrade Items"
  | "Memories"
  | "Relics"
  | "Sanctified Relics"
  | "Sanctum Research"
  | "Sentinel Drones"
  | "Tinctures"
  | "Charms"
  | "Corpses"
  | "Gold"
  | (string & {})
