export type LifeFlasks =
  | "Small Life Flask"
  | "Medium Life Flask"
  | "Large Life Flask"
  | "Greater Life Flask"
  | "Grand Life Flask"
  | "Giant Life Flask"
  | "Colossal Life Flask"
  | "Sacred Life Flask"
  | "Hallowed Life Flask"
  | "Sanctified Life Flask"
  | "Divine Life Flask"
  | "Eternal Life Flask"
  | (string & {})
