export type MapFragments =
  | "Sacrifice at Dusk"
  | "Sacrifice at Midnight"
  | "Sacrifice at Dawn"
  | "Sacrifice at Noon"
  | "Mortal Grief"
  | "Mortal Rage"
  | "Mortal Hope"
  | "Mortal Ignorance"
  | "Fragment of the Hydra"
  | "Fragment of the Phoenix"
  | "Fragment of the Minotaur"
  | "Fragment of the Chimera"
  | "Divine Vessel"
  | "Offering to the Goddess"
  | "An Audience With The King"
  | "Craicic Lure"
  | "Farric Lure"
  | "Fenumal Lure"
  | "Saqawine Lure"
  | "Timeless Karui Emblem"
  | "Timeless Maraketh Emblem"
  | "Timeless Eternal Emblem"
  | "Timeless Templar Emblem"
  | "Timeless Vaal Emblem"
  | "Fragment of Enslavement"
  | "Fragment of Eradication"
  | "Fragment of Constriction"
  | "Fragment of Purification"
  | "Fragment of Shape"
  | "Fragment of Knowledge"
  | "Fragment of Terror"
  | "Fragment of Emptiness"
  | "Simulacrum"
  | "Tribute to the Goddess"
  | "Gift to the Goddess"
  | "Dedication to the Goddess"
  | "Blood-filled Vessel"
  | "The Maven's Writ"
  | "Sacred Blossom"
  | "Unrelenting Timeless Karui Emblem"
  | "Unrelenting Timeless Maraketh Emblem"
  | "Unrelenting Timeless Eternal Emblem"
  | "Unrelenting Timeless Templar Emblem"
  | "Unrelenting Timeless Vaal Emblem"
  | "Al-Hezmin's Crest"
  | "Baran's Crest"
  | "Drox's Crest"
  | "Veritania's Crest"
  | "Cosmic Fragment"
  | "Decaying Fragment"
  | "Awakening Fragment"
  | "Synthesising Fragment"
  | "Reality Fragment"
  | "Devouring Fragment"
  | "Blazing Fragment"
  | "Breach Scarab"
  | "Breach Scarab of the Dreamer"
  | "Breach Scarab of Lordship"
  | "Breach Scarab of Splintering"
  | "Breach Scarab of Snares"
  | "Cartography Scarab of Escalation"
  | "Cartography Scarab of Risk"
  | "Cartography Scarab of Singularity"
  | "Cartography Scarab of Corruption"
  | "Cartography Scarab of the Multitude"
  | "Titanic Scarab"
  | "Titanic Scarab of Treasures"
  | "Titanic Scarab of Legend"
  | "Bestiary Scarab"
  | "Bestiary Scarab of the Herd"
  | "Bestiary Scarab of Duplicating"
  | "Bestiary Scarab of the Shadowed Crow"
  | "Influencing Scarab of the Shaper"
  | "Influencing Scarab of the Elder"
  | "Influencing Scarab of Hordes"
  | "Influencing Scarab of Conversion"
  | "Sulphite Scarab"
  | "Sulphite Scarab of Greed"
  | "Sulphite Scarab of Fumes"
  | "Divination Scarab of The Cloister"
  | "Divination Scarab of Plenty"
  | "Divination Scarab of Pilfering"
  | "Torment Scarab"
  | "Torment Scarab of Peculiarity"
  | "Torment Scarab of Release"
  | "Ambush Scarab"
  | "Ambush Scarab of Hidden Compartments"
  | "Ambush Scarab of Potency"
  | "Ambush Scarab of Containment"
  | "Ambush Scarab of Discernment"
  | "Harbinger Scarab"
  | "Harbinger Scarab of Obelisks"
  | "Harbinger Scarab of Regency"
  | "Harbinger Scarab of Warhoards"
  | "Expedition Scarab"
  | "Expedition Scarab of Runefinding"
  | "Expedition Scarab of Verisium Powder"
  | "Expedition Scarab of the Skald"
  | "Expedition Scarab of Archaeology"
  | "Legion Scarab"
  | "Legion Scarab of Officers"
  | "Legion Scarab of Command"
  | "Legion Scarab of The Sekhema"
  | "Legion Scarab of Eternal Conflict"
  | "Abyss Scarab"
  | "Abyss Scarab of Multitudes"
  | "Abyss Scarab of Edifice"
  | "Abyss Scarab of Emptiness"
  | "Anarchy Scarab"
  | "Anarchy Scarab of Gigantification"
  | "Anarchy Scarab of Partnership"
  | "Essence Scarab"
  | "Essence Scarab of Ascent"
  | "Essence Scarab of Stability"
  | "Essence Scarab of Calcification"
  | "Domination Scarab"
  | "Domination Scarab of Apparitions"
  | "Domination Scarab of Evolution"
  | "Domination Scarab of Terrors"
  | "Ritual Scarab of Selectiveness"
  | "Ritual Scarab of Wisps"
  | "Ritual Scarab of Abundance"
  | "Harvest Scarab"
  | "Harvest Scarab of Doubling"
  | "Harvest Scarab of Cornucopia"
  | "Incursion Scarab"
  | "Incursion Scarab of Invasion"
  | "Incursion Scarab of Champions"
  | "Incursion Scarab of Timelines"
  | "Betrayal Scarab"
  | "Betrayal Scarab of Intelligence"
  | "Betrayal Scarab of Reinforcements"
  | "Betrayal Scarab of Perpetuation"
  | "Beyond Scarab"
  | "Beyond Scarab of Corruption"
  | "Beyond Scarab of Haemophilia"
  | "Beyond Scarab of Resurgence"
  | "Beyond Scarab of the Invasion"
  | "Ultimatum Scarab"
  | "Ultimatum Scarab of Bribing"
  | "Ultimatum Scarab of Dueling"
  | "Ultimatum Scarab of Catalysing"
  | "Ultimatum Scarab of Inscription"
  | "Delirium Scarab"
  | "Delirium Scarab of Mania"
  | "Delirium Scarab of Paranoia"
  | "Delirium Scarab of Neuroses"
  | "Delirium Scarab of Delusions"
  | "Blight Scarab"
  | "Blight Scarab of Bounty"
  | "Blight Scarab of the Blightheart"
  | "Blight Scarab of Blooming"
  | "Scarab of Monstrous Lineage"
  | "Scarab of Adversaries"
  | "Scarab of Divinity"
  | "Scarab of Hunted Traitors"
  | "Scarab of Stability"
  | "Horned Scarab of Bloodlines"
  | "Horned Scarab of Nemeses"
  | "Horned Scarab of Preservation"
  | "Horned Scarab of Awakening"
  | "Horned Scarab of Tradition"
  | "Horned Scarab of Glittering"
  | "Horned Scarab of Pandemonium"
  | "Abyss Scarab of Profound Depth"
  | "Blight Scarab of Invigoration"
  | "Breach Scarab of Resonant Cascade"
  | "Essence Scarab of Adaptation"
  | "Torment Scarab of Possession"
  | "Scarab of Radiant Storms"
  | "Scarab of Wisps"
  | "Scarab of Bisection"
  | (string & {})
