export type Maps =
  | "Academy Map"
  | "Acid Caverns Map"
  | "Alleyways Map"
  | "Ancient City Map"
  | "Arachnid Nest Map"
  | "Arachnid Tomb Map"
  | "Arcade Map"
  | "Arena Map"
  | "Arid Lake Map"
  | "Armoury Map"
  | "Arsenal Map"
  | "Ashen Wood Map"
  | "Atoll Map"
  | "Barrows Map"
  | "Basilica Map"
  | "Bazaar Map"
  | "Beach Map"
  | "Belfry Map"
  | "Bog Map"
  | "Bone Crypt Map"
  | "Bramble Valley Map"
  | "Burial Chambers Map"
  | "Cage Map"
  | "Caldera Map"
  | "Canyon Map"
  | "Carcass Map"
  | "Castle Ruins Map"
  | "Cells Map"
  | "Cemetery Map"
  | "Channel Map"
  | "Chateau Map"
  | "City Square Map"
  | "Cold River Map"
  | "Colonnade Map"
  | "Colosseum Map"
  | "Conservatory Map"
  | "Coral Ruins Map"
  | "Core Map"
  | "Courthouse Map"
  | "Courtyard Map"
  | "Coves Map"
  | "Crater Map"
  | "Crimson Temple Map"
  | "Crimson Township Map"
  | "Crystal Ore Map"
  | "Cursed Crypt Map"
  | "Dark Forest Map"
  | "Defiled Cathedral Map"
  | "Desert Map"
  | "Desert Spring Map"
  | "Dig Map"
  | "Dry Sea Map"
  | "Dunes Map"
  | "Dungeon Map"
  | "Estuary Map"
  | "Excavation Map"
  | "Factory Map"
  | "Fields Map"
  | "Flooded Mine Map"
  | "Forbidden Woods Map"
  | "Forge of the Phoenix Map"
  | "Forking River Map"
  | "Foundry Map"
  | "Frozen Cabins Map"
  | "Fungal Hollow Map"
  | "Gardens Map"
  | "Geode Map"
  | "Ghetto Map"
  | "Glacier Map"
  | "Grave Trough Map"
  | "Graveyard Map"
  | "Grotto Map"
  | "Haunted Mansion Map"
  | "Iceberg Map"
  | "Infested Valley Map"
  | "Ivory Temple Map"
  | "Jungle Valley Map"
  | "Laboratory Map"
  | "Lair Map"
  | "Lair of the Hydra Map"
  | "Lava Chamber Map"
  | "Lava Lake Map"
  | "Leyline Map"
  | "Lighthouse Map"
  | "Lookout Map"
  | "Malformation Map"
  | "Marshes Map"
  | "Mausoleum Map"
  | "Maze Map"
  | "Maze of the Minotaur Map"
  | "Mesa Map"
  | "Mineral Pools Map"
  | "Moon Temple Map"
  | "Mud Geyser Map"
  | "Museum Map"
  | "Necropolis Map"
  | "Orchard Map"
  | "Overgrown Ruin Map"
  | "Overgrown Shrine Map"
  | "Palace Map"
  | "Park Map"
  | "Pen Map"
  | "Peninsula Map"
  | "Phantasmagoria Map"
  | "Pier Map"
  | "Pit Map"
  | "Pit of the Chimera Map"
  | "Plateau Map"
  | "Plaza Map"
  | "Port Map"
  | "Primordial Blocks Map"
  | "Primordial Pool Map"
  | "Promenade Map"
  | "Racecourse Map"
  | "Ramparts Map"
  | "Reef Map"
  | "Relic Chambers Map"
  | "Residence Map"
  | "Scriptorium Map"
  | "Sepulchre Map"
  | "Shipyard Map"
  | "Shore Map"
  | "Shrine Map"
  | "Siege Map"
  | "Silo Map"
  | "Spider Forest Map"
  | "Spider Lair Map"
  | "Stagnation Map"
  | "Strand Map"
  | "Sulphur Vents Map"
  | "Summit Map"
  | "Sunken City Map"
  | "Temple Map"
  | "Terrace Map"
  | "Thicket Map"
  | "Tower Map"
  | "Toxic Sewer Map"
  | "Tropical Island Map"
  | "Underground River Map"
  | "Underground Sea Map"
  | "Vaal Pyramid Map"
  | "Vaal Temple Map"
  | "Vault Map"
  | "Villa Map"
  | "Volcano Map"
  | "Waste Pool Map"
  | "Wasteland Map"
  | "Waterways Map"
  | "Wharf Map"
  | "Precinct Map"
  | "Sanctuary Map"
  | "Citadel Map"
  | "Fortress Map"
  | "Abomination Map"
  | "Ziggurat Map"
  | "Harbinger Map"
  | "Synthesised Map"
  | "Engraved Ultimatum"
  | (string & {})
