export type QuestItems =
  | "Medicine Chest"
  | "Ammonite Glyph"
  | "Haliotis Glyph"
  | "Roseus Glyph"
  | "Allflame"
  | "Baleful Gem"
  | "Maligaro's Spike"
  | "Thaumetic Emblem"
  | "Alira's Amulet"
  | "Kraityn's Amulet"
  | "Oak's Amulet"
  | "The Apex"
  | "Golden Hand"
  | "Tolman's Bracelet"
  | "Sewer Keys"
  | "Bust of Gaius Sentari"
  | "Bust of Hector Titucius"
  | "Bust of Marceus Lioneye"
  | "Ribbon Spool"
  | "Thaumetic Sulphite"
  | "Infernal Talc"
  | "Tower Key"
  | "Golden Page"
  | "Decanter Spiritus"
  | "Chitus' Plum"
  | "Deshret's Banner"
  | "The Eye of Desire"
  | "The Eye of Fury"
  | "Malachai's Entrails"
  | "Malachai's Heart"
  | "Malachai's Lungs"
  | "Miasmeter"
  | "Eyes of Zeal"
  | "Sign of Purity"
  | "Hinekora's Hair"
  | "Tukohama's Tooth"
  | "Valako's Jaw"
  | "Bestel's Manuscript"
  | "Eye of Conquest"
  | "The Black Flag"
  | "Maligaro's Map"
  | "Black Venom"
  | "Obsidian Key"
  | "Firefly"
  | "Kishara's Star"
  | "Silver Locket"
  | "Greust's Necklace"
  | "Ankh of Eternity"
  | "Wings of Vastiri"
  | "Sun Orb"
  | "Moon Orb"
  | "Storm Blade"
  | "Bottled Storm"
  | "Calendar of Fortune"
  | "Basilisk Acid"
  | "Trarthan Powder"
  | "Sekhema Feather"
  | "The Staff of Purity"
  | "The Teardrop"
  | "Elixir of Allure"
  | "Memory Fragment"
  | "Shaper's Orb"
  | "Elder's Orb"
  | "The Shaper's Key"
  | "Master Key"
  | "Atlas Book of Skill"
  | "Flesh Compass"
  | "Luminous Astrolabe"
  | "Contract: Antique Urn"
  | "Contract: Stolen Lockpicks"
  | "Contract: Karst's Revenge"
  | "Contract: Credit Where Credit's Due"
  | "Contract: Finding Opal"
  | "Contract: Opal's Jewels"
  | "Contract: Enoch's Whereabouts"
  | "Contract: Enoch's Remains"
  | "Contract: Grocery List"
  | "Contract: The Vinderi Bomb"
  | "Contract: The Nameless Play"
  | "Contract: The Finest Costumes"
  | "Contract: The Wedding Dress"
  | "Contract: Disengagement"
  | "Contract: Rational Tools"
  | "Contract: A Mundane Sample"
  | "Contract: The Book of Jamanra"
  | "Contract: Isla's Prototypes"
  | "Contract: Isla's Designs"
  | "Contract: A Matter of Honour"
  | "Contract: Flying False Colours"
  | "Contract: Slaver's Revenge"
  | "Contract: Follow the Paper Trail"
  | "Contract: The Admiral's Records"
  | "Contract: Findings for Fidium"
  | "Contract: Hyrri's Gift"
  | "Contract: The Negotiation"
  | "Contract: The Rescue"
  | (string & {})
