export type Rings =
  | "Breach Ring"
  | "Coral Ring"
  | "Iron Ring"
  | "Paua Ring"
  | "Unset Ring"
  | "Sapphire Ring"
  | "Topaz Ring"
  | "Ruby Ring"
  | "Diamond Ring"
  | "Gold Ring"
  | "Moonstone Ring"
  | "Two-Stone Ring"
  | "Amethyst Ring"
  | "Prismatic Ring"
  | "Opal Ring"
  | "Steel Ring"
  | "Vermillion Ring"
  | "Cerulean Ring"
  | "Bone Ring"
  | "Dusk Ring"
  | "Penumbra Ring"
  | "Gloam Ring"
  | "Tenebrous Ring"
  | "Shadowed Ring"
  | "Ring"
  | "Nameless Ring"
  | "Iolite Ring"
  | "Cogwork Ring"
  | "Geodesic Ring"
  | "Composite Ring"
  | "Manifold Ring"
  | "Ratcheting Ring"
  | "Helical Ring"
  | "Golden Hoop"
  | (string & {})
