export type RuneDaggers =
  | "Carving Knife"
  | "Boot Knife"
  | "Copper Kris"
  | "Skean"
  | "Imp Dagger"
  | "Butcher Knife"
  | "Boot Blade"
  | "Golden Kris"
  | "Royal Skean"
  | "Fiend Dagger"
  | "Slaughter Knife"
  | "Ezomyte Dagger"
  | "Platinum Kris"
  | "Imperial Skean"
  | "Demon Dagger"
  | "Flickerflame Blade"
  | "Flashfire Blade"
  | "Infernal Blade"
  | (string & {})
