export type VaultKeys =
  | "Ancient Reliquary Key"
  | "Timeworn Reliquary Key"
  | "Vaal Reliquary Key"
  | "Forgotten Reliquary Key"
  | "Visceral Reliquary Key"
  | "Shiny Reliquary Key"
  | "Archive Reliquary Key"
  | "Oubliette Reliquary Key"
  | "Cosmic Reliquary Key"
  | "Decaying Reliquary Key"
  | "Voidborn Reliquary Key"
  | (string & {})
