import rule from "../../../rule"
import type { BaseType, Color, ItemClass, Mixin, NumberRange, Operator, Rarity, Rule, Shape } from "../../../types"
import type * as Autogenerated from "../../../types/autogenerated"
import { SoundFile } from "../../../types/sounds/generated-sounds"
import { filterDefaults } from "../defaults"
import { filterStyles, soundFile, styleMixin } from "../styles"

// Shared item-class constants
export const ARMOUR_CLASSES = ["Body Armours", "Gloves", "Boots", "Helmets"] as const satisfies readonly ItemClass[]
export const SOCKETABLE_CLASSES = [...ARMOUR_CLASSES, "Shields"] as const satisfies readonly ItemClass[]
export const WEAPON_CLASSES = [
  "One Hand Axes",
  "Two Hand Axes",
  "Bows",
  "Claws",
  "Daggers",
  "Rune Daggers",
  "One Hand Maces",
  "Sceptres",
  "Two Hand Maces",
  "Staves",
  "Warstaves",
  "One Hand Swords",
  "Thrusting One Hand Swords",
  "Two Hand Swords",
  "Wands",
  "Fishing Rods",
] as const satisfies readonly WeaponItemClass[]
export const REMAINING_EQUIPMENT_CLASSES = [
  ...WEAPON_CLASSES,
  ...SOCKETABLE_CLASSES,
  "Amulets",
  "Belts",
  "Quivers",
  "Rings",
  "Jewels",
  "Abyss Jewels",
  "Life Flasks",
  "Mana Flasks",
  "Hybrid Flasks",
  "Utility Flasks",
  "Heist Cloaks",
  "Heist Brooches",
  "Heist Tools",
  "Heist Gear",
  "Tinctures",
  "Charms",
] as const satisfies readonly ItemClass[]

const SLOT_SOUND_SUFFIX: Record<(typeof ARMOUR_CLASSES)[number] | "Shields", string> = {
  "Body Armours": "body",
  "Gloves": "gloves",
  "Boots": "boots",
  "Helmets": "helm",
  "Shields": "shield",
}

// Shared config types
export type DefenceBaseType = "armour" | "evasion" | "es" | "armour-evasion" | "armour-es" | "es-evasion"
export type SocketColor = "R" | "G" | "B"
export type TwoLinkPattern = "RR" | "RG" | "RB" | "GG" | "GB" | "BB"
export type ThreeLinkPattern = "RRR" | "RRG" | "RRB" | "RGG" | "RGB" | "RBB" | "GGG" | "GGB" | "GBB" | "BBB"
export type FourLinkPattern =
  | "RRRR"
  | "RRRG"
  | "RRRB"
  | "RRGG"
  | "RRGB"
  | "RRBB"
  | "RGGG"
  | "RGGB"
  | "RGBB"
  | "RBBB"
  | "GGGG"
  | "GGGB"
  | "GGBB"
  | "GBBB"
  | "BBBB"
export type SocketPattern = TwoLinkPattern | ThreeLinkPattern | FourLinkPattern
export type WeaponItemClass =
  | "One Hand Axes"
  | "Two Hand Axes"
  | "Bows"
  | "Claws"
  | "Daggers"
  | "Rune Daggers"
  | "One Hand Maces"
  | "Sceptres"
  | "Two Hand Maces"
  | "Staves"
  | "Warstaves"
  | "One Hand Swords"
  | "Thrusting One Hand Swords"
  | "Two Hand Swords"
  | "Wands"
  | "Fishing Rods"
export type WeaponBaseType =
  | Autogenerated.Bows
  | Autogenerated.Claws
  | Autogenerated.Daggers
  | Autogenerated.FishingRods
  | Autogenerated.OneHandAxes
  | Autogenerated.OneHandMaces
  | Autogenerated.OneHandSwords
  | Autogenerated.RuneDaggers
  | Autogenerated.Sceptres
  | Autogenerated.Staves
  | Autogenerated.ThrustingOneHandSwords
  | Autogenerated.TwoHandAxes
  | Autogenerated.TwoHandMaces
  | Autogenerated.TwoHandSwords
  | Autogenerated.Wands
  | Autogenerated.Warstaves

export type BuildProfile = {
  preferredArmourTypes: readonly DefenceBaseType[]
  preferredWeaponItemClasses?: readonly WeaponItemClass[]
  shieldProgression?: ShieldProgressionConfig
}

export type BuildSpecificOptions = {
  links: LinksConfig
  socketBases?: SocketBasesConfig
  jewellery?: JewelleryConfig
  rareItems?: RareItemsConfig
  magicItems?: MagicItemsConfig
  normalItems?: NormalItemsConfig
  tinctures?: TincturesConfig
  highlightedEquipment?: HighlightedEquipmentConfig
  early?: EarlyConfig
  earlySockets?: EarlySocketsConfig
}

export type SocketPatternConfig<TPattern extends SocketPattern = SocketPattern> = {
  pattern: TPattern
  maxAreaLevel?: number
  itemClasses?: readonly ((typeof ARMOUR_CLASSES)[number] | "Shields")[]
}

export type GenericFourLinkConfig = {
  defenceType: DefenceBaseType
  maxAreaLevel?: number
}

export type LinksConfig = {
  twoLinkPatterns?: readonly (TwoLinkPattern | SocketPatternConfig<TwoLinkPattern>)[]
  twoLinkMaxAreaLevel?: number
  threeLinkPatterns?: readonly (ThreeLinkPattern | SocketPatternConfig<ThreeLinkPattern>)[]
  threeLinkMaxAreaLevel?: number
  genericThreeLinks?: boolean
  fourLinkPatterns?: readonly (FourLinkPattern | SocketPatternConfig<FourLinkPattern>)[]
  genericFourLinksEnabled?: boolean
  genericFourLinks?: readonly (DefenceBaseType | GenericFourLinkConfig)[]
}

export type SocketBasesConfig = {
  maxAreaLevel?: number
  desiredThreeSocketGroups?: readonly TwoLinkPattern[]
  desiredThreeSocketMaxAreaLevel?: number
}

export type RareItemsConfig = {
  weaponItemClasses?: readonly WeaponItemClass[]
  maxAreaLevel?: number
}

export type ChromaticItemsConfig = {
  smallMaxAreaLevel?: number
  largeMaxAreaLevel?: number
}

export type LevelingAmuletBaseType = "Amber" | "Jade" | "Lapis"

export type JewelleryConfig = {
  amulets?: readonly LevelingAmuletBaseType[]
}

export type WeaponHighlightConfig = {
  baseTypes?: readonly WeaponBaseType[]
  itemClasses?: readonly WeaponItemClass[]
  maxAreaLevel?: number
}

export type HighlightedBaseTypeConfig = {
  baseTypes?: readonly BaseType[]
  itemClasses?: readonly ItemClass[]
  rarityOperator?: Operator
  rarity?: Rarity
  rarities?: readonly Rarity[]
  maxAreaLevel?: number
  soundId?: NumberRange<1, 17>
  soundFileName?: SoundFile
}

export type EarlyConfig = {
  weaponHighlights?: readonly WeaponHighlightConfig[]
  earlyMaxAreaLevel?: number
  showRustic?: boolean
  includeMomentumColors?: boolean
  momentumColors?: {
    itemClasses?: readonly ItemClass[]
    baseTypes?: readonly BaseType[]
    maxAreaLevel?: number
  }
  momentumMaxAreaLevel?: number
}

export type HighlightedEquipmentConfig = {
  highlights?: readonly HighlightedBaseTypeConfig[]
}

export type MagicItemsConfig = {
  maxAreaLevel?: number
}

export type ItemSectionConfig = {
  weaponItemClasses?: readonly WeaponItemClass[]
  weaponBaseTypes?: readonly WeaponBaseType[]
}

export type NormalItemsConfig = ItemSectionConfig & {
  maxAreaLevel?: number
}

export type EarlySocketsConfig = ItemSectionConfig

export type ShieldProgressionMode = "none" | "early" | "full"

export type ShieldProgressionConfig =
  | ShieldProgressionMode
  | {
      mode?: ShieldProgressionMode
      maxAreaLevel?: number
    }

export type TincturesConfig = {
  baseTypes?: readonly Autogenerated.Tinctures[]
}

// Section composition helpers
export const compileRules = (...rules: Array<Rule | null | undefined | false>) => {
  const activeRules = rules.filter(Boolean) as Rule[]
  if (activeRules.length === 0) return ""
  return rule(...activeRules).compile()
}

export const joinSections = (...sections: string[]) =>
  sections
    .map((section) => section.trim())
    .filter(Boolean)
    .join("\n\n")

export const optionalSection = <T>(config: T | undefined, build: (config: T) => string) => (config ? build(config) : "")

export const comment = (text: string, level: 1 | 2 | 3 = 1) => `${"#".repeat(level)} ${text}`

export const withHeading = (heading: string, ...sections: string[]) => joinSections(comment(heading, 3), ...sections)

export const withSubheading = (heading: string, ...sections: string[]) => joinSections(comment(heading, 1), ...sections)

// Shared lookup data
export const defenceMixinMap: Record<DefenceBaseType, Mixin> = {
  "armour": (target) => target.baseArmour(">=", 1).baseES("==", 0).baseEvasion("==", 0),
  "evasion": (target) => target.baseArmour("==", 0).baseES("==", 0).baseEvasion(">=", 1),
  "es": (target) => target.baseArmour("==", 0).baseES(">=", 1).baseEvasion("==", 0),
  "armour-evasion": (target) => target.baseArmour(">=", 1).baseES("==", 0).baseEvasion(">=", 1),
  "armour-es": (target) => target.baseArmour(">=", 1).baseES(">=", 1).baseEvasion("==", 0),
  "es-evasion": (target) => target.baseArmour("==", 0).baseES(">=", 1).baseEvasion(">=", 1),
}

export const getSocketPatternSoundPrefix = (pattern: ThreeLinkPattern | FourLinkPattern) =>
  pattern.length === 3 && ["R", "G", "B"].every((color) => pattern.includes(color))
    ? "chrome"
    : (["R", "G", "B"] as const)
        .map((color) => ({ color, count: pattern.split("").filter((entry) => entry === color).length }))
        .filter(({ count }) => count > 0)
        .sort((left, right) => {
          const colorPriority = { R: 0, G: 1, B: 2 } as const
          return right.count - left.count || colorPriority[left.color] - colorPriority[right.color]
        })
        .map(({ color, count }) => `${count}${color.toLowerCase()}`)
        .join("")

export const genericFourLinkSoundMap: Record<DefenceBaseType, string> = {
  "armour": "4_link_armour",
  "armour-evasion": "4_link_armour_evasion",
  "armour-es": "4_link_armour_es",
  "evasion": "4_link_evasion",
  "es": "4_link_es",
  "es-evasion": "4_link_evasion_es",
}

// Config normalizers
export const normalizeSocketPatternConfig = <TPattern extends SocketPattern>(
  entry: TPattern | SocketPatternConfig<TPattern>,
): SocketPatternConfig<TPattern> => (typeof entry === "string" ? { pattern: entry } : entry)

export const normalizeGenericFourLinkConfig = (entry: DefenceBaseType | GenericFourLinkConfig): GenericFourLinkConfig =>
  typeof entry === "string" ? { defenceType: entry } : entry

export const normalizeShieldProgressionConfig = (shieldProgression?: ShieldProgressionConfig) => {
  const defaultMode = filterDefaults.shieldProgression.mode
  const earlyMaxAreaLevel = filterDefaults.shieldProgression.earlyMaxAreaLevel

  if (typeof shieldProgression === "string" || shieldProgression === undefined) {
    const mode = shieldProgression ?? defaultMode

    if (mode === "none") {
      return { enabled: false, maxAreaLevel: earlyMaxAreaLevel }
    }

    if (mode === "full") {
      return { enabled: true, maxAreaLevel: undefined }
    }

    return { enabled: true, maxAreaLevel: earlyMaxAreaLevel }
  }

  const mode = shieldProgression.mode ?? defaultMode

  if (mode === "none") {
    return { enabled: false, maxAreaLevel: shieldProgression.maxAreaLevel ?? earlyMaxAreaLevel }
  }

  if (mode === "full") {
    return { enabled: true, maxAreaLevel: shieldProgression.maxAreaLevel }
  }

  return {
    enabled: true,
    maxAreaLevel: shieldProgression.maxAreaLevel ?? earlyMaxAreaLevel,
  }
}

export const getShieldProgressionMode = (shieldProgression?: ShieldProgressionConfig): ShieldProgressionMode =>
  typeof shieldProgression === "string" ? shieldProgression : (shieldProgression?.mode ?? filterDefaults.shieldProgression.mode)

// Generic rule builders
export const applyHighlightTargets = (
  target: Rule,
  { baseTypes, itemClasses }: { baseTypes?: readonly BaseType[]; itemClasses?: readonly ItemClass[] },
) => {
  if (baseTypes && baseTypes.length > 0) {
    target.baseType(...baseTypes)
  }

  if (itemClasses && itemClasses.length > 0) {
    target.itemClass(...itemClasses)
  }

  return target
}

export const buildItemClassSocketRules = ({
  linkedSockets,
  pattern,
  itemClasses = ARMOUR_CLASSES,
  soundPrefix,
  iconColor,
  maxAreaLevel,
  style = styleMixin(filterStyles.fourLink),
}: {
  linkedSockets?: 2 | 3 | 4
  pattern: string
  itemClasses?: readonly ((typeof ARMOUR_CLASSES)[number] | "Shields")[]
  soundPrefix?: string
  iconColor: Color
  maxAreaLevel?: number
  style?: Mixin
}) =>
  itemClasses.map((itemClass) => {
    const builtRule = rule().itemClass(itemClass).socketGroup("==", pattern).icon(iconColor, "Diamond").mixin(style)

    if (maxAreaLevel !== undefined) {
      builtRule.areaLevel("<=", maxAreaLevel)
    }

    if (linkedSockets !== undefined) {
      builtRule.linkedSockets("==", linkedSockets)
    }

    if (!soundPrefix) {
      return builtRule
    }

    return builtRule.customSound(soundFile(`${soundPrefix}_${SLOT_SOUND_SUFFIX[itemClass]}.mp3`))
  })

export const buildGenericFourLinkRules = ({
  defenceType,
  maxAreaLevel = filterDefaults.links.fourLinkMaxAreaLevel,
}: GenericFourLinkConfig) =>
  ARMOUR_CLASSES.map((itemClass) =>
    rule()
      .itemClass(itemClass)
      .linkedSockets("==", 4)
      .areaLevel("<=", maxAreaLevel)
      .mixin(defenceMixinMap[defenceType])
      .icon("Cyan", "Diamond")
      .mixin(styleMixin(filterStyles.fourLink))
      .customSound(soundFile(`${genericFourLinkSoundMap[defenceType]}_${SLOT_SOUND_SUFFIX[itemClass]}.mp3`)),
  )

const highlightedEquipmentStyleMap = {
  Rare: filterStyles.highlightedEquipmentRare,
  Magic: filterStyles.highlightedEquipmentMagic,
  Normal: filterStyles.highlightedEquipmentNormal,
} as const satisfies Record<"Rare" | "Magic" | "Normal", (typeof filterStyles)[keyof typeof filterStyles]>

const HIGHLIGHTABLE_RARITIES = ["Normal", "Magic", "Rare"] as const satisfies readonly Rarity[]
type HighlightableRarity = (typeof HIGHLIGHTABLE_RARITIES)[number]

const getRaritiesForOperator = (operator: Operator, rarity: HighlightableRarity) => {
  const pivotIndex = HIGHLIGHTABLE_RARITIES.indexOf(rarity)

  switch (operator) {
    case "<":
      return HIGHLIGHTABLE_RARITIES.slice(0, pivotIndex)
    case "<=":
      return HIGHLIGHTABLE_RARITIES.slice(0, pivotIndex + 1)
    case ">":
      return HIGHLIGHTABLE_RARITIES.slice(pivotIndex + 1)
    case ">=":
      return HIGHLIGHTABLE_RARITIES.slice(pivotIndex)
    case "!=":
      return HIGHLIGHTABLE_RARITIES.filter((entry) => entry !== rarity)
    case "=":
    case "==":
    default:
      return [rarity]
  }
}

export const buildHighlightedBaseTypeRules = ({
  baseTypes,
  itemClasses,
  rarityOperator,
  rarity,
  rarities,
  maxAreaLevel,
  soundId,
  soundFileName,
}: HighlightedBaseTypeConfig) => {
  const appliedRarities = rarities?.length
    ? rarities.filter((entry): entry is HighlightableRarity => HIGHLIGHTABLE_RARITIES.includes(entry as HighlightableRarity))
    : rarityOperator && rarity && HIGHLIGHTABLE_RARITIES.includes(rarity as HighlightableRarity)
      ? getRaritiesForOperator(rarityOperator, rarity as HighlightableRarity)
      : [...HIGHLIGHTABLE_RARITIES]
  const buildRule = (selectedRarity?: Rarity) => {
    const style =
      selectedRarity && selectedRarity in highlightedEquipmentStyleMap
        ? highlightedEquipmentStyleMap[selectedRarity as keyof typeof highlightedEquipmentStyleMap]
        : filterStyles.highlightedEquipment
    const builtRule = applyHighlightTargets(rule().icon("Cyan", "UpsideDownHouse").mixin(styleMixin(style)), { baseTypes, itemClasses })

    if (maxAreaLevel !== undefined) {
      builtRule.areaLevel("<=", maxAreaLevel)
    }

    if (soundFileName) {
      builtRule.customSound(soundFile(soundFileName))
    } else if (soundId !== undefined) {
      builtRule.sound(soundId)
    }

    return builtRule
  }

  return appliedRarities.map((selectedRarity) => buildRule(selectedRarity).rarity("==", selectedRarity))
}

// Section-specific data builders
export const buildTierCurrency = (
  style: keyof typeof filterStyles,
  entries: Array<{ baseTypes: string[]; iconColor: Color; iconShape: Shape; soundId?: NumberRange<1, 17>; soundFileName?: SoundFile }>,
) =>
  compileRules(
    rule(
      ...entries.map(({ baseTypes, iconColor, iconShape, soundId, soundFileName }) => {
        const builtRule = rule()
          .baseType(...baseTypes)
          .icon(iconColor, iconShape)

        if (soundFileName) {
          builtRule.customSound(soundFile(soundFileName))
        } else if (soundId !== undefined) {
          builtRule.sound(soundId)
        }

        return builtRule
      }),
    ).mixin(styleMixin(filterStyles[style])),
  )

// Flask builders
export const buildFlaskRule = ({
  baseTypes,
  itemClass,
  rarity,
  maxAreaLevel,
  iconColor,
  sound,
  style,
}: {
  baseTypes: readonly string[]
  itemClass: "Life Flasks" | "Mana Flasks"
  rarity: "Normal" | "Magic"
  maxAreaLevel?: number
  iconColor: Color
  sound: string
  style: Mixin
}) => {
  const builtRule = rule()
    .itemClass(itemClass)
    .baseType(...baseTypes)
    .rarity("==", rarity)
    .icon(iconColor, "Raindrop")
    .mixin(style)

  if (maxAreaLevel !== undefined) {
    builtRule.areaLevel("<=", maxAreaLevel)
  }

  return builtRule.customSound(soundFile(sound))
}

export const buildFlaskSeries = ({
  itemClass,
  iconColor,
  style,
  entries,
}: {
  itemClass: "Life Flasks" | "Mana Flasks"
  iconColor: Color
  style: "lifeFlask" | "manaFlask"
  entries: Array<{ baseTypes: string[]; maxAreaLevel?: number; soundFileName: SoundFile }>
}) =>
  entries.flatMap(({ baseTypes, maxAreaLevel, soundFileName }) => [
    buildFlaskRule({
      itemClass,
      baseTypes,
      rarity: "Normal",
      maxAreaLevel,
      iconColor,
      sound: soundFileName,
      style: styleMixin(filterStyles[style]),
    }),
    buildFlaskRule({
      itemClass,
      baseTypes,
      rarity: "Magic",
      maxAreaLevel,
      iconColor,
      sound: soundFileName,
      style: styleMixin(filterStyles[style]),
    }),
  ])

export const buildUtilityFlaskRules = (entries: Array<{ baseType: string; soundFileName: SoundFile }>) =>
  entries.map(({ baseType, soundFileName }) =>
    rule()
      .itemClass("Utility Flasks")
      .baseType(baseType)
      .icon("Green", "Raindrop")
      .mixin(styleMixin(filterStyles.utilityFlask))
      .customSound(soundFile(soundFileName)),
  )
