import type { BaseType, Color, ItemClass, NumberRange, Shape } from "../../../types"
import type * as Autogenerated from "../../../types/autogenerated"
import { MANIFEST_BY_ID, type SoundManifestEntry } from "../../../sounds/manifest"
import { filterDefaults } from "../defaults"
import type { DefenceBaseType } from "./item-classes"

export type LinkColor = "R" | "G" | "B"
export type TtsFile = string | SoundManifestEntry
export type ShieldProgressionMode = "none" | "early" | "full"
export type ShieldProgressionConfig = ShieldProgressionMode

export type BuildProfile = {
  preferredArmour?: readonly DefenceBaseType[]
  preferredWeapons?: HighlightedBaseTypeConfig
  earlyWeapons?: HighlightedBaseTypeConfig
  shieldProgression?: ShieldProgressionConfig
  preferredColors?: readonly LinkColor[]
}

export type LinksConfig = {
  twoLinkMaxAreaLevel?: number
  threeLinkMaxAreaLevel?: number
  fourLinkMaxAreaLevel?: number
  genericThreeLinksEnabled?: boolean
  genericFourLinksEnabled?: boolean
  fourLinkTtsCutoffLevel?: number
  threeLinkTtsCutoffLevel?: number
}

export type JewelleryConfig = {
  amulets?: readonly LevelingAmuletConfig[]
  amuletMaxAreaLevel?: number
  basicRingMaxAreaLevel?: number
  elementalRingMaxAreaLevel?: number
  beltMaxAreaLevel?: number
}

export type RareItemsConfig = {
  /** Hard cutoff: rare items at or below this area level are shown. Unset means uncapped. */
  maxAreaLevel?: number
}
export type MagicItemsConfig = { maxAreaLevel?: number }
export type NormalItemsConfig = { maxAreaLevel?: number }
export type TincturesConfig = { baseTypes?: readonly Autogenerated.Tinctures[] }
export type EarlyConfig = {
  earlyMaxAreaLevel?: number
  twoSocketMaxAreaLevel?: number
  threeSocketMaxAreaLevel?: number
  earlyBootsMaxAreaLevel?: number
}
export type HighlightableRarity = "Normal" | "Magic" | "Rare"

export const HIGHLIGHTABLE_RARITIES = ["Normal", "Magic", "Rare"] as const satisfies readonly HighlightableRarity[]

export type RarityHighlightConfig = {
  iconColor?: Color
  iconShape?: Shape
  soundId?: NumberRange<1, 16>
  soundFileName?: string
  tts?: TtsFile
}

export type HighlightedBaseTypeConfig = {
  name?: string
  baseTypes?: readonly BaseType[]
  itemClasses?: readonly ItemClass[]
  minAps?: number
  linkedSockets?: number
  minSockets?: number
  weaponCutoffOverlap?: number
  rarities?: readonly HighlightableRarity[]
  minAreaLevel?: number
  maxAreaLevel?: number
  minItemLevel?: number
  maxItemLevel?: number
  /** When true, styling (icon/sound) is configured per rarity; the top-level icon/sound is ignored. */
  perRarityCustomization?: boolean
  /** Whole-highlight icon and sound, applied to every rarity unless `perRarityCustomization` is set. */
  iconColor?: Color
  iconShape?: Shape
  soundId?: NumberRange<1, 16>
  soundFileName?: string
  tts?: TtsFile
  normal?: RarityHighlightConfig
  magic?: RarityHighlightConfig
  rare?: RarityHighlightConfig
}

export type HighlightedEquipmentConfig = { highlights?: readonly HighlightedBaseTypeConfig[] }

export type BuildSpecificOptions = {
  links?: LinksConfig
  jewellery?: JewelleryConfig
  rareItems?: RareItemsConfig
  magicItems?: MagicItemsConfig
  normalItems?: NormalItemsConfig
  tinctures?: TincturesConfig
  highlightedEquipment?: HighlightedEquipmentConfig
  early?: EarlyConfig
}

/** Maps a highlightable rarity to the config key holding its per-rarity styling. */
export const RARITY_CONFIG_KEY: Record<HighlightableRarity, "normal" | "magic" | "rare"> = {
  Normal: "normal",
  Magic: "magic",
  Rare: "rare",
}

export const resolveShieldProgressionMode = (shieldProgression?: ShieldProgressionConfig): ShieldProgressionMode =>
  shieldProgression ?? filterDefaults.shieldProgression

export const LEVELING_AMULETS = {
  Amber: { baseType: "Amber Amulet", entry: MANIFEST_BY_ID.amber_amulet },
  Jade: { baseType: "Jade Amulet", entry: MANIFEST_BY_ID.jade_amulet },
  Lapis: { baseType: "Lapis Amulet", entry: MANIFEST_BY_ID.lapis_amulet },
  Turquoise: { baseType: "Turquoise Amulet", entry: MANIFEST_BY_ID.turquoise_amulet },
  Citrine: { baseType: "Citrine Amulet", entry: MANIFEST_BY_ID.citrine_amulet },
  Agate: { baseType: "Agate Amulet", entry: MANIFEST_BY_ID.agate_amulet },
  Onyx: { baseType: "Onyx Amulet", entry: MANIFEST_BY_ID.onyx_amulet },
} as const

export type LevelingAmuletShortBaseType = keyof typeof LEVELING_AMULETS
export type LevelingAmuletConfig = LevelingAmuletShortBaseType | { shortBaseType: LevelingAmuletShortBaseType }
export const normalizeLevelingAmuletConfig = (entry: LevelingAmuletConfig) => {
  const shortBaseType = typeof entry === "string" ? entry : entry.shortBaseType
  const defaults = LEVELING_AMULETS[shortBaseType]
  return { baseType: defaults.baseType, shortBaseType, entry: defaults.entry }
}
