import "dotenv/config"
import { execSync, spawn, type ChildProcess } from "child_process"
import fs from "fs"
import path from "path"
import { ensureSettings, repoRoot } from "../config/settings"

const FRONTEND_PORT = 5173
const API_PORT = Number(process.env.PORT || 3001)

const isWindows = process.platform === "win32"

/** Runs a command through the shell so `npm` resolves on every platform. */
function run(command: string, args: string[]): void {
  execSync([command, ...args].join(" "), { stdio: "inherit", cwd: repoRoot() })
}

/** True when the local binary for `bin` (e.g. "ts-node", "vite") is installed. */
function hasLocalBin(bin: string): boolean {
  const names = isWindows ? [`${bin}.cmd`, bin] : [bin]
  return names.some((name) => fs.existsSync(path.join(repoRoot(), "node_modules", ".bin", name)))
}

function installIfNeeded(): void {
  // Check for the binaries the server (ts-node) and frontend (vite) actually
  // need, so a missing or incomplete node_modules still triggers an install.
  if (hasLocalBin("ts-node") && hasLocalBin("vite")) return
  console.log("Installing dependencies…")
  run("npm", ["install"])
}

function ensureTypes(): void {
  const itemClasses = path.join(repoRoot(), "src", "types", "autogenerated", "ItemClasses.ts")
  if (fs.existsSync(itemClasses)) return
  console.log("Generating types…")
  run("npm", ["run", "generate"])
}

function openBrowser(url: string): void {
  if (isWindows) {
    spawn("cmd", ["/c", "start", "", url], { stdio: "ignore", detached: true }).unref()
    return
  }
  const command = process.platform === "darwin" ? "open" : "xdg-open"
  spawn(command, [url], { stdio: "ignore", detached: true }).unref()
}

function spawnNpx(args: string[]): ChildProcess {
  // On Windows `npx` is a `.cmd` shim that only runs through a shell.
  return spawn("npx", args, { stdio: "inherit", cwd: repoRoot(), shell: isWindows })
}

function start(): void {
  process.env.VITE_CONFIG_NATIVE_IGNORE_WARNING = "true"
  const children = [
    spawnNpx(["--no-install", "ts-node", "./src/server/index.ts"]),
    spawnNpx(["--no-install", "vite", "--config", "frontend/vite.config.ts"]),
  ]

  setTimeout(() => openBrowser(`http://localhost:${FRONTEND_PORT}`), 2500)

  const shutdown = () => {
    for (const child of children) child.kill()
    process.exit(0)
  }
  process.on("SIGINT", shutdown)
  process.on("SIGTERM", shutdown)
}

export function main(): void {
  installIfNeeded()
  ensureSettings()
  ensureTypes()
  console.log(`filtertool starting — API on :${API_PORT}, UI on :${FRONTEND_PORT}`)
  start()
}

if (require.main === module) {
  main()
}
