import "dotenv/config"
import { execSync, spawn } from "child_process"
import fs from "fs"
import path from "path"
import { ensureSettings, repoRoot } from "../config/settings"

const FRONTEND_PORT = 5173
const API_PORT = Number(process.env.PORT || 3001)

function run(command: string, args: string[]): void {
  execSync([command, ...args].join(" "), { stdio: "inherit", cwd: repoRoot() })
}

function installIfNeeded(): void {
  if (fs.existsSync(path.join(repoRoot(), "node_modules"))) return
  console.log("Installing dependencies…")
  run("npm", ["install"])
}

function ensureTypes(): void {
  const itemClasses = path.join(repoRoot(), "src", "types", "autogenerated", "ItemClasses.ts")
  if (fs.existsSync(itemClasses)) return
  console.log("Generating types…")
  run("npm", ["run", "generate"])
}

function openBrowser(url: string): void {
  const platform = process.platform
  const command = platform === "darwin" ? "open" : platform === "win32" ? "start" : "xdg-open"
  spawn(command, [url], { stdio: "ignore", detached: true }).unref()
}

function start(): void {
  process.env.VITE_CONFIG_NATIVE_IGNORE_WARNING = "true"
  const children = [
    spawn("npx", ["--no-install", "ts-node", "./src/server/index.ts"], { stdio: "inherit", cwd: repoRoot() }),
    spawn("npx", ["--no-install", "vite", "--config", "frontend/vite.config.ts"], { stdio: "inherit", cwd: repoRoot() }),
  ]

  setTimeout(() => openBrowser(`http://localhost:${FRONTEND_PORT}`), 2500)

  const shutdown = () => {
    for (const child of children) child.kill()
    process.exit(0)
  }
  process.on("SIGINT", shutdown)
  process.on("SIGTERM", shutdown)
}

export function main(): void {
  installIfNeeded()
  ensureSettings()
  ensureTypes()
  console.log(`filtertool starting — API on :${API_PORT}, UI on :${FRONTEND_PORT}`)
  start()
}

if (require.main === module) {
  main()
}
