import "dotenv/config"
import fs from "fs"
import path from "path"
import { format, resolveConfig } from "prettier"
import { SOUND_PACK_SOURCE_DIR } from "../sounds/paths"

const SOURCE_DIR = `./${SOUND_PACK_SOURCE_DIR}`
const OUTPUT_FILE = "./src/types/sounds/generated-sounds.ts"

function getSourceDir(): string {
  if (!fs.existsSync(SOURCE_DIR)) {
    fs.mkdirSync(SOURCE_DIR, { recursive: true })
  }
  return SOURCE_DIR
}

async function writeFormattedFile(filePath: string, content: string) {
  const prettierConfig = await resolveConfig(filePath)
  const formattedContent = await format(content, { ...prettierConfig, filepath: filePath })
  fs.writeFileSync(filePath, formattedContent)
}

export async function generateSoundTypes() {
  const sourceDir = getSourceDir()
  const files = fs.readdirSync(sourceDir).sort((left, right) => {
    const insens = left.toLowerCase().localeCompare(right.toLowerCase(), "en")
    return insens !== 0 ? insens : left.localeCompare(right, "en")
  })

  const typeContent = files.length
    ? `// This file is autogenerated by src/scripts/generateSoundTypes.ts\nexport type SoundFile =\n${files.map((name: string) => `  | ${JSON.stringify(name)}`).join("\n")}`
    : "export type SoundFile = string"

  if (!fs.existsSync(path.dirname(OUTPUT_FILE))) {
    fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true })
  }

  await writeFormattedFile(OUTPUT_FILE, typeContent)
}

async function main() {
  await generateSoundTypes()
}

if (require.main === module) {
  void main()
}
