import {
  chromaticItems,
  currency,
  divinationCards,
  early,
  earlySockets,
  flasks,
  gems,
  hideEquipment,
  highlightedEquipment,
  jewellery,
  joinSections,
  links,
  magicItems,
  normalItems,
  misc,
  optionalSection,
  questItems,
  rareItems,
  scrolls,
  showUnknownItems,
  sixSockets,
  tinctures,
  twilightStrand,
  uniques,
} from "../shared"
import { buildProfile, buildSpecificOptions } from "./config"

export const getFilter = () =>
  joinSections(
    twilightStrand(),
    currency(),
    scrolls(),
    uniques(),
    gems(),
    links({ ...buildProfile, ...buildSpecificOptions.links }),
    sixSockets(),
    optionalSection(buildSpecificOptions.highlightedEquipment, highlightedEquipment),
    jewellery(buildSpecificOptions.jewellery),
    optionalSection(buildSpecificOptions.early, (config) => early({ ...buildProfile, ...config })),
    optionalSection(buildSpecificOptions.earlySockets, (config) => earlySockets({ ...buildProfile, ...config })),
    flasks(),
    optionalSection(buildSpecificOptions.tinctures, tinctures),
    chromaticItems(),
    optionalSection(buildSpecificOptions.rareItems, (config) => rareItems({ ...buildProfile, ...config })),
    optionalSection(buildSpecificOptions.magicItems, magicItems),
    optionalSection(buildSpecificOptions.normalItems, (config) => normalItems({ ...buildProfile, ...config })),
    questItems(),
    divinationCards(),
    misc(),
    hideEquipment(),
    showUnknownItems(),
  )
