import {
  AbyssJewels,
  Amulets,
  AtlasUpgradeItems,
  Belts,
  Blueprints,
  BodyArmours,
  Boots,
  Bows,
  Breachstones,
  Charms,
  Claws,
  Contracts,
  Corpses,
  Daggers,
  DelveStackableSocketableCurrency,
  DivinationCards,
  ExpeditionLogbooks,
  FishingRods,
  Gloves,
  Gold,
  HeistBrooches,
  HeistCloaks,
  HeistGear,
  HeistTargets,
  HeistTools,
  Helmets,
  HybridFlasks,
  Incubators,
  IncursionItems,
  ItemClasses,
  Jewels,
  LabyrinthItems,
  LabyrinthTrinkets,
  LifeFlasks,
  ManaFlasks,
  MapFragments,
  Maps,
  Memories,
  MiscMapItems,
  OneHandAxes,
  OneHandMaces,
  OneHandSwords,
  Pieces,
  QuestItems,
  Quivers,
  Relics,
  Rings,
  RuneDaggers,
  SanctifiedRelics,
  SanctumResearch,
  Sceptres,
  SentinelDrones,
  Shields,
  SkillGems,
  StackableCurrency,
  Staves,
  SupportGems,
  ThrustingOneHandSwords,
  Tinctures,
  Trinkets,
  TwoHandAxes,
  TwoHandMaces,
  TwoHandSwords,
  UtilityFlasks,
  VaultKeys,
  Wands,
  Warstaves,
} from "./autogenerated"

export type BaseType =
  | AbyssJewels
  | Amulets
  | AtlasUpgradeItems
  | Belts
  | Blueprints
  | BodyArmours
  | Boots
  | Bows
  | Breachstones
  | Charms
  | Claws
  | Contracts
  | Corpses
  | Daggers
  | DelveStackableSocketableCurrency
  | DivinationCards
  | ExpeditionLogbooks
  | FishingRods
  | Gloves
  | Gold
  | HeistBrooches
  | HeistCloaks
  | HeistGear
  | HeistTargets
  | HeistTools
  | Helmets
  | HybridFlasks
  | Incubators
  | IncursionItems
  | Jewels
  | LabyrinthItems
  | LabyrinthTrinkets
  | LifeFlasks
  | ManaFlasks
  | MapFragments
  | Maps
  | Memories
  | MiscMapItems
  | OneHandAxes
  | OneHandMaces
  | OneHandSwords
  | Pieces
  | QuestItems
  | Quivers
  | Relics
  | Rings
  | RuneDaggers
  | SanctifiedRelics
  | SanctumResearch
  | Sceptres
  | SentinelDrones
  | Shields
  | SkillGems
  | StackableCurrency
  | Staves
  | SupportGems
  | ThrustingOneHandSwords
  | Tinctures
  | Trinkets
  | TwoHandAxes
  | TwoHandMaces
  | TwoHandSwords
  | UtilityFlasks
  | VaultKeys
  | Wands
  | Warstaves

export type ItemClass = ItemClasses
