export type ExplicitMods =
  | "Abating"
  | "Abbot's"
  | "Abecedarian's"
  | "Abundant"
  | "Acidic"
  | "Acolyte's"
  | "Acrobat's"
  | "Acuminate"
  | "Acute"
  | "Adaptable"
  | "Adept's"
  | "Adroit"
  | "Affecting"
  | "Aged"
  | "Agile"
  | "Agonizing"
  | "Alarmed"
  | "Alchemist's"
  | "Allocated"
  | "Alpine"
  | "Ample"
  | "Analyst's"
  | "Anarchist's"
  | "Annealed"
  | "Annest's"
  | "Anointed"
  | "Antagonist's"
  | "Apparition's"
  | "Apprentice's"
  | "Aqua"
  | "Archmage's"
  | "Arcing"
  | "Arctic"
  | "Ardent"
  | "Armadillo's"
  | "Arming"
  | "Armoured"
  | "Artificer's"
  | "Assailant's"
  | "Athlete's"
  | "Atrophic"
  | "Atrophying"
  | "Augur's"
  | "Auspex's"
  | "Avalanching"
  | "Avenger's"
  | "Azure"
  | "Baleful"
  | "Bandit's"
  | "Barbed"
  | "Baron's"
  | "Baroness's"
  | "Battlemage's"
  | "Beatified"
  | "Beating"
  | "Beautiful"
  | "Beclouded"
  | "Beetle's"
  | "Behemoth's"
  | "Beryl"
  | "Betrayer's"
  | "Bishop's"
  | "Biting"
  | "Bitter"
  | "Blacksmith's"
  | "Blasting"
  | "Blazing"
  | "Bleak"
  | "Blessed"
  | "Blistering"
  | "Bloodied"
  | "Bloodletter's"
  | "Bloodthirsty"
  | "Blue"
  | "Blunt"
  | "Blurred"
  | "Blurring"
  | "Boggart's"
  | "Bolstered"
  | "Bolting"
  | "Boreal"
  | "Bottomless"
  | "Bountiful"
  | "Brass-knuckle"
  | "Brawler's"
  | "Brawling"
  | "Breathtaking"
  | "Brewer's"
  | "Brinerot"
  | "Brownsmith's"
  | "Brutal"
  | "Brute's"
  | "Bubbling"
  | "Bull's"
  | "Bully's"
  | "Burning"
  | "Burnished"
  | "Butterfly's"
  | "Buttressed"
  | "Buzzing"
  | "Cadigan's"
  | "Calcified"
  | "Calligraphic"
  | "Calming"
  | "Captivating"
  | "Carapaced"
  | "Carbonising"
  | "Careful"
  | "Carved"
  | "Caster's"
  | "Catalysed"
  | "Catalysing"
  | "Catalyzing"
  | "Catarina's"
  | "Catarina's Veiled"
  | "Caustic"
  | "Cauterising"
  | "Cautious"
  | "Cerulean"
  | "Chalybeous"
  | "Champion's"
  | "Chanter's"
  | "Chaotic"
  | "Charged"
  | "Charging"
  | "Chastising"
  | "Chayula's"
  | "Cheetah's"
  | "Chemist's"
  | "Cherub's"
  | "Cherufe's"
  | "Chilled"
  | "Chilling"
  | "Chimeral's"
  | "Chiseled"
  | "Chosen"
  | "Citaqualotl's"
  | "Cleaving"
  | "Clinician's"
  | "Clouded"
  | "Cobalt"
  | "Coelacanth's"
  | "Combatant's"
  | "Competitor's"
  | "Concentrated"
  | "Condensed"
  | "Condensing"
  | "Congealed"
  | "Conjuror's"
  | "Conqueror's"
  | "Consecrated"
  | "Constant"
  | "Continuous"
  | "Coppersmith's"
  | "Corrosive"
  | "Corrupting"
  | "Count's"
  | "Countess's"
  | "Coursing"
  | "Crab's"
  | "Crackling"
  | "Cremating"
  | "Crippling"
  | "Crocodile's"
  | "Cruel"
  | "Crusader's"
  | "Cryomancer's"
  | "Cryomantic"
  | "Crystalising"
  | "Crystalline"
  | "Dabbler's"
  | "Dancer's"
  | "Darkened"
  | "Dauntless"
  | "Dazzling"
  | "Deacon's"
  | "Debilitating"
  | "Deceiver's"
  | "Decrepifying"
  | "Defensive"
  | "Deflecting"
  | "Degenerative"
  | "Deleterious"
  | "Delinquent's"
  | "Depleting"
  | "Deteriorating"
  | "Determined"
  | "Devastating"
  | "Dictator's"
  | "Discharging"
  | "Disintegrating"
  | "Dissipating"
  | "Dissolving"
  | "Distilling"
  | "Dizzying"
  | "Djinn's"
  | "Doctor's"
  | "Doled"
  | "Dolomite"
  | "Dragon's"
  | "Dragonfly's"
  | "Draining"
  | "Druid's"
  | "Duchess's"
  | "Duelist's"
  | "Duke's"
  | "Durable"
  | "Eagle's"
  | "Earnest"
  | "Ebullient"
  | "Effervescent"
  | "Effusive"
  | "Eidolon's"
  | "Electrocuting"
  | "Electromantic"
  | "Elegant"
  | "Elephant's"
  | "Elevated Crusader's"
  | "Elevated Elder's"
  | "Elevated Hunter's"
  | "Elevated Redeemer's"
  | "Elevated Shaper's"
  | "Elevated Warlord's"
  | "Elreon's"
  | "Elreon's Veiled"
  | "Elusory"
  | "Embedded"
  | "Emperor's"
  | "Empowering"
  | "Empress's"
  | "Encased"
  | "Endless"
  | "Enduring"
  | "Energetic"
  | "Energising"
  | "Engraved"
  | "Engraver's"
  | "Enhanced"
  | "Enlightened"
  | "Entombing"
  | "Enveloped"
  | "Ephemeral"
  | "Esh's"
  | "Essences"
  | "Etched"
  | "Eternal"
  | "Ethereal"
  | "Evanescent"
  | "Evasive"
  | "Exalter's"
  | "Examiner's"
  | "Exarch's"
  | "Exciting"
  | "Excruciating"
  | "Exemplary"
  | "Expediting"
  | "Experimenter's"
  | "Exquisite"
  | "Exsanguinating"
  | "Exuberant"
  | "Facilitating"
  | "Faithful"
  | "Fanatical"
  | "Farrier's"
  | "Fawn's"
  | "Fearless"
  | "Fecund"
  | "Fencer's"
  | "Fencing"
  | "Fermented"
  | "Fervid"
  | "Festering"
  | "Fevered"
  | "Fierce"
  | "Fighter's"
  | "Filigree"
  | "Flagellant's"
  | "Flame Shaper's"
  | "Flame Spinner's"
  | "Flaming"
  | "Flanking"
  | "Flaring"
  | "Flawless"
  | "Flea's"
  | "Fleet"
  | "Fletcher's"
  | "Flexible"
  | "Foreboding"
  | "Fortified"
  | "Foul-tongued"
  | "Freezing"
  | "Frightened"
  | "Frigid"
  | "Frost Singer's"
  | "Frost Weaver's"
  | "Frosted"
  | "Frozen"
  | "Fuelling"
  | "Fugitive"
  | "Full-bodied"
  | "Furious"
  | "Galvanizing"
  | "Gazelle's"
  | "Gelid"
  | "Gentian"
  | "Ghost's"
  | "Ghostly"
  | "Girded"
  | "Glaciated"
  | "Gladiator's"
  | "Gleaming"
  | "Glimmering"
  | "Glinting"
  | "Glittering"
  | "Glowing"
  | "Glyphic"
  | "Godly"
  | "Goldsmith's"
  | "Gravicius'"
  | "Gravicius' Veiled"
  | "Gremlin's"
  | "Guatelitzi's"
  | "Guff's Veiled"
  | "Gwayne's"
  | "Gypsum"
  | "Hailing"
  | "Haku's"
  | "Haku's Veiled"
  | "Hale"
  | "Hallowed"
  | "Halting"
  | "Harbinger's"
  | "Harming"
  | "Harmonic"
  | "Harrowing"
  | "Haruspex's"
  | "Hasty"
  | "Healthy"
  | "Heartening"
  | "Heartstopping"
  | "Heated"
  | "Heavy"
  | "Hellion's"
  | "Hemorrhaging"
  | "Hero's"
  | "Hissing"
  | "Honed"
  | "Humming"
  | "Hummingbird's"
  | "Hungering"
  | "Hunter's"
  | "Ibex's"
  | "Icy"
  | "Illusion's"
  | "Illusory"
  | "Impairing"
  | "Impaling"
  | "Impenetrable"
  | "Impervious"
  | "Impregnable"
  | "Improved"
  | "Incandescent"
  | "Incanter's"
  | "Incapacitating"
  | "Incinerating"
  | "Incisive"
  | "Inclement"
  | "Incorporeal"
  | "Inculcated"
  | "Indomitable"
  | "Inescapable"
  | "Infernal"
  | "Infixed"
  | "Infused"
  | "Infusing"
  | "Ingrained"
  | "Inimical"
  | "Inscribed"
  | "Inspirational"
  | "Inspired"
  | "Inspiring"
  | "Instilled"
  | "Interceptor's"
  | "Interpermeated"
  | "Interpolated"
  | "Investigator's"
  | "Ionising"
  | "It That Fled's Veiled"
  | "It's"
  | "Jagged"
  | "Jinxing"
  | "Jogger's"
  | "Journeyman's"
  | "Judging"
  | "Kainite"
  | "Kieserite"
  | "King's"
  | "Kingfisher's"
  | "Kirac's"
  | "Korell's"
  | "Korell's Veiled"
  | "Lacerating"
  | "Lacquered"
  | "Lamprey's"
  | "Lancing"
  | "Lava Caller's"
  | "Lava Conjurer's"
  | "Layered"
  | "Leadership"
  | "Learned"
  | "Legend's"
  | "Leo's"
  | "Leo's Veiled"
  | "Lethal"
  | "Lettered"
  | "Lich's"
  | "Lissome"
  | "Lithomancer's"
  | "Lively"
  | "Lobstered"
  | "Lodestone"
  | "Mad Lord's"
  | "Mage's"
  | "Magister's"
  | "Magmatic"
  | "Magnifying"
  | "Magpie's"
  | "Malicious"
  | "Malignant"
  | "Mammoth's"
  | "Marchioness's"
  | "Marquess's"
  | "Martinet's"
  | "Masochist's"
  | "Master's"
  | "Masterwork"
  | "Matatl's"
  | "Mazarine"
  | "Measured"
  | "Medic's"
  | "Mercenary's"
  | "Merciless"
  | "Mirage's"
  | "Monk's"
  | "Mortifying"
  | "Mosquito's"
  | "Moth's"
  | "Motivating"
  | "Murmuring"
  | "Mutewind"
  | "Naga's"
  | "Nautilus's"
  | "Necromancer's"
  | "Nightmare's"
  | "Nihilist's"
  | "Nitrate"
  | "Nymph's"
  | "Obliterating"
  | "Occultist's"
  | "Opalescent"
  | "Opaque"
  | "Otherworldly"
  | "Overpowering"
  | "Overseer's"
  | "Owen's"
  | "Owl's"
  | "Oyster's"
  | "Paladin's"
  | "Panicked"
  | "Paragon's"
  | "Parched"
  | "Parrying"
  | "Passionate"
  | "Perandus'"
  | "Perforating"
  | "Pernicious"
  | "Perpetual"
  | "Phantasm's"
  | "Phased"
  | "Phlebotomising"
  | "Physician's"
  | "Piercing"
  | "Pirate's"
  | "Pixie's"
  | "Plated"
  | "Plentiful"
  | "Pliant"
  | "Polar"
  | "Polished"
  | "Practitioner's"
  | "Predator's"
  | "Prepared"
  | "Priest's"
  | "Prime"
  | "Prince's"
  | "Princess's"
  | "Prior's"
  | "Professor's"
  | "Protective"
  | "Provisioned"
  | "Provocateur's"
  | "Prudent"
  | "Pulsing"
  | "Puncturing"
  | "Punishing"
  | "Pyroclastic"
  | "Pyromantic"
  | "Queen's"
  | "Quetzacoatl's"
  | "Quintessential"
  | "Radiating"
  | "Ram's"
  | "Rapturous"
  | "Rationed"
  | "Razor-sharp"
  | "Reanimator's"
  | "Reaver's"
  | "Recovering"
  | "Redblade"
  | "Redeemer's"
  | "Refreshing"
  | "Regenerating"
  | "Reinforced"
  | "Reinforcing"
  | "Rejuvenating"
  | "Reliable"
  | "Remora's"
  | "Renewing"
  | "Resilient"
  | "Resolute"
  | "Resonant"
  | "Resonating"
  | "Resplendent"
  | "Restoring"
  | "Rhex's"
  | "Rhino's"
  | "Rhoa's"
  | "Ribbed"
  | "Rimedweller's"
  | "Rin's"
  | "Rin's Veiled"
  | "Ripping"
  | "Robust"
  | "Rogue's"
  | "Rotted"
  | "Rotund"
  | "Runed"
  | "Runemaster's"
  | "Runesmith's"
  | "Runic"
  | "Runner's"
  | "Rupturing"
  | "Sabotage"
  | "Saintly"
  | "Sanctified"
  | "Sanguine"
  | "Sapphire"
  | "Sapping"
  | "Saturated"
  | "Savage"
  | "Scholar's"
  | "Scintillating"
  | "Scorching"
  | "Scrapper's"
  | "Searing"
  | "Seeping"
  | "Seething"
  | "Seraphim's"
  | "Serene"
  | "Serrated"
  | "Shade's"
  | "Shadowy"
  | "Shaman's"
  | "Shark's"
  | "Sharpened"
  | "Sharpshooter's"
  | "Shielding"
  | "Shimmering"
  | "Shining"
  | "Shocking"
  | "Silversmith's"
  | "Simmering"
  | "Sinister"
  | "Sinner's"
  | "Siphoning"
  | "Sizzling"
  | "Skewering"
  | "Slicing"
  | "Smiting"
  | "Smoking"
  | "Smouldering"
  | "Snapping"
  | "Snowy"
  | "Soldier's"
  | "Sorcerer's"
  | "Sparking"
  | "Specialist's"
  | "Spectre's"
  | "Spilling"
  | "Spiny"
  | "Spirit's"
  | "Spirited"
  | "Splintermind's"
  | "Splitting"
  | "Sprinter's"
  | "Spurring"
  | "Squire's"
  | "Stallion's"
  | "Stalwart"
  | "Startled"
  | "Stirring"
  | "Stormbrewer's"
  | "Stout"
  | "Striking"
  | "Strong-Willed"
  | "Studded"
  | "Sturdy"
  | "Substantial"
  | "Subterranean"
  | "Suffixed"
  | "Summoner's"
  | "Sundering"
  | "Supple"
  | "Surgeon's"
  | "Surging"
  | "Swordfish's"
  | "Sylph's"
  | "Tacati's"
  | "Tainted"
  | "Taskmaster's"
  | "Technical"
  | "Tecton's"
  | "Tempered"
  | "Tempest King's"
  | "Tempest Master's"
  | "Termpermental"
  | "Terrified"
  | "Thaumaturgist's"
  | "The Elder's"
  | "The Shaper's"
  | "Thickened"
  | "Thirsting"
  | "Thirsty"
  | "Thorny"
  | "Thug's"
  | "Thunder Lord's"
  | "Thunderhand's"
  | "Thundering"
  | "Thwarting"
  | "Topotante's"
  | "Tora's"
  | "Tora's Veiled"
  | "Transfusing"
  | "Transgressor's"
  | "Trapping"
  | "Trenchant"
  | "Tul's"
  | "Turbid"
  | "Turncoat's"
  | "Tyrannical"
  | "Ultramarine"
  | "Unassailable"
  | "Undiluted"
  | "Unfailing"
  | "Unfaltering"
  | "Unleashed"
  | "Unmoving"
  | "Unreal"
  | "Unworldly"
  | "Upgraded"
  | "Urchin's"
  | "Uul-Netol's"
  | "Vagan's"
  | "Vagan's Veiled"
  | "Vampire's"
  | "Vaporous"
  | "Vapourising"
  | "Veiled"
  | "Versatile"
  | "Vicious"
  | "Victor's"
  | "Vigorous"
  | "Vile"
  | "Virile"
  | "Viscount's"
  | "Viscountess's"
  | "Viscous"
  | "Vitiating"
  | "Vivacious"
  | "Vivid"
  | "Volcanic"
  | "Volleying"
  | "Vorici's"
  | "Vorici's Veiled"
  | "Vulcanist's"
  | "Vulture's"
  | "Waning"
  | "Warding"
  | "Warlock's"
  | "Warlord's"
  | "Warrior's"
  | "Wary"
  | "Wasp's"
  | "Wasting"
  | "Weaponmaster's"
  | "Wendigo's"
  | "Whale's"
  | "Whitesmith's"
  | "Wicked"
  | "Wide"
  | "Will-o-wisp's"
  | "Winter Beckoner's"
  | "Winterbringer's"
  | "Wise"
  | "Withering"
  | "Wizard's"
  | "Wraith's"
  | "Wright's"
  | "Xopec's"
  | "Xoph's"
  | "Youthful"
  | "Zaffre"
  | "Zealous"
  | "of Abjuration"
  | "of Absorption"
  | "of Abundance"
  | "of Abuse"
  | "of Acclaim"
  | "of Acclimatisation"
  | "of Accuracy"
  | "of Acrimony"
  | "of Adamantite Skin"
  | "of Adaptation"
  | "of Adaption"
  | "of Adjustment"
  | "of Agitation"
  | "of Agony"
  | "of Aisling"
  | "of Aisling's Veil"
  | "of Allaying"
  | "of Alleviation"
  | "of Amassment"
  | "of Anger"
  | "of Annihilation"
  | "of Archaeology"
  | "of Archery"
  | "of Arcing"
  | "of Ardour"
  | "of Ashes"
  | "of Assuaging"
  | "of Asylum"
  | "of Athletics"
  | "of Atrophy"
  | "of Atrophying"
  | "of Authority"
  | "of Balance"
  | "of Ballast"
  | "of Bameth"
  | "of Bandaging"
  | "of Banishing"
  | "of Banishment"
  | "of Berserking"
  | "of Blasphemy"
  | "of Blasting"
  | "of Bleakness"
  | "of Bleeding"
  | "of Blinding"
  | "of Bliss"
  | "of Blocking"
  | "of Bloodletting"
  | "of Bloodshed"
  | "of Blurring"
  | "of Bog Moss"
  | "of Bounty"
  | "of Bracing"
  | "of Brimming"
  | "of Buffering"
  | "of Burning"
  | "of Butchery"
  | "of Calamity"
  | "of Calm"
  | "of Cameria"
  | "of Cameria's Veil"
  | "of Carnage"
  | "of Casting"
  | "of Celebration"
  | "of Charging"
  | "of Chayula"
  | "of Chilling"
  | "of Cinders"
  | "of Citaqualotl"
  | "of Clay"
  | "of Clouding"
  | "of Coals"
  | "of Coercion"
  | "of Collecting"
  | "of Collision"
  | "of Combat"
  | "of Combusting"
  | "of Combustion"
  | "of Command"
  | "of Composure"
  | "of Concord"
  | "of Confidence"
  | "of Conflagrating"
  | "of Conflagration"
  | "of Conservation"
  | "of Consumption"
  | "of Control"
  | "of Convalescence"
  | "of Convection"
  | "of Coordination"
  | "of Corundum Skin"
  | "of Counterpoise"
  | "of Cover"
  | "of Craft"
  | "of Crafting"
  | "of Craiceann"
  | "of Craving"
  | "of Cunning"
  | "of Curing"
  | "of Dampening"
  | "of Damping"
  | "of Darting"
  | "of Daunting"
  | "of Dazing"
  | "of Deadening"
  | "of Deadliness"
  | "of Death"
  | "of Deflection"
  | "of Delaying"
  | "of Demolishing"
  | "of Depletion"
  | "of Destruction"
  | "of Deteriorating"
  | "of Dexterity"
  | "of Diffusion"
  | "of Disaster"
  | "of Discharge"
  | "of Dishonour"
  | "of Disintegrating"
  | "of Dispersal"
  | "of Dispersion"
  | "of Dissolution"
  | "of Distraction"
  | "of Diverting"
  | "of Dousing"
  | "of Draining"
  | "of Dueling"
  | "of Dulling"
  | "of Earthing"
  | "of Ease"
  | "of Efficiency"
  | "of Elation"
  | "of Electricity"
  | "of Electrocution"
  | "of Elevated Redemption"
  | "of Elevated Shaping"
  | "of Embers"
  | "of Enchanting"
  | "of Endurance"
  | "of Enervation"
  | "of Enlivening"
  | "of Entropy"
  | "of Ephij"
  | "of Escape"
  | "of Esh"
  | "of Esprit"
  | "of Euphoria"
  | "of Everlasting"
  | "of Eviction"
  | "of Evolution"
  | "of Excavation"
  | "of Excitement"
  | "of Exile"
  | "of Expertise"
  | "of Expulsion"
  | "of Exsanguinating"
  | "of Exsanguination"
  | "of Extinguishing"
  | "of Exuberance"
  | "of Fame"
  | "of Farrul"
  | "of Fascination"
  | "of Fearlessness"
  | "of Fending"
  | "of Fenumus"
  | "of Ferocity"
  | "of Fervour"
  | "of Finesse"
  | "of Fireproofing"
  | "of Flames"
  | "of Flaying"
  | "of Fleshbinding"
  | "of Flight"
  | "of Floe"
  | "of Focus"
  | "of Fog"
  | "of Foisting"
  | "of Force"
  | "of Fortitude"
  | "of Freedom"
  | "of Freezing"
  | "of Frenzy"
  | "of Furs"
  | "of Fury"
  | "of Galvanising"
  | "of Gathering"
  | "of Gelidity"
  | "of Glaciation"
  | "of Gluttony"
  | "of Gore"
  | "of Grandmastery"
  | "of Grounding"
  | "of Guarding"
  | "of Guatelitzi"
  | "of Haast"
  | "of Haemophilia"
  | "of Hardiness"
  | "of Harm"
  | "of Harmony"
  | "of Haste"
  | "of Havoc"
  | "of Haze"
  | "of Heartstopping"
  | "of Heat"
  | "of Heating"
  | "of Heft"
  | "of Hemorrhaging"
  | "of Hexing"
  | "of Hexwarding"
  | "of Hillock"
  | "of Hillock's Veil"
  | "of Hindering"
  | "of Hoarding"
  | "of Ice"
  | "of Ignition"
  | "of Immolation"
  | "of Immortality"
  | "of Impact"
  | "of Impaling"
  | "of Impedance"
  | "of Imposing"
  | "of Incantations"
  | "of Incessance"
  | "of Incision"
  | "of Incitation"
  | "of Infamy"
  | "of Infliction"
  | "of Infuriation"
  | "of Instigation"
  | "of Instinct"
  | "of Instruction"
  | "of Insulating"
  | "of Insulation"
  | "of Intelligence"
  | "of Intercepting"
  | "of Interference"
  | "of Invocations"
  | "of Ire"
  | "of Iron Skin"
  | "of Janus"
  | "of Janus' Veil"
  | "of Jorgin's Veil"
  | "of Joy"
  | "of Languishing"
  | "of Legerdemain"
  | "of Liberation"
  | "of Life-giving"
  | "of Light"
  | "of Lioneye"
  | "of Liquefaction"
  | "of Longevity"
  | "of Malevolence"
  | "of Malice"
  | "of Maneuvering"
  | "of Mangling"
  | "of Many"
  | "of Marshalling"
  | "of Masterminding"
  | "of Mastery"
  | "of Matatl"
  | "of Melting"
  | "of Menace"
  | "of Mending"
  | "of Mist"
  | "of Momentum"
  | "of Motion"
  | "of Motivation"
  | "of Movement"
  | "of Mysticism"
  | "of Needling"
  | "of Nimbleness"
  | "of Nirvana"
  | "of Nonflammability"
  | "of Nourishment"
  | "of Nullification"
  | "of Numbing"
  | "of Obstruction"
  | "of Occlusion"
  | "of Onslaught"
  | "of Opportunity"
  | "of Orchestration"
  | "of Order"
  | "of Osmosis"
  | "of Overflowing"
  | "of Penetrating"
  | "of Perenniality"
  | "of Permafreeze"
  | "of Perpetuity"
  | "of Persistence"
  | "of Phasing"
  | "of Phlebotomising"
  | "of Piercing"
  | "of Plenty"
  | "of Plume Moss"
  | "of Plunder"
  | "of Poise"
  | "of Poison"
  | "of Poisoning"
  | "of Potency"
  | "of Pouring"
  | "of Power"
  | "of Praxis"
  | "of Prayers"
  | "of Precision"
  | "of Prefixes"
  | "of Preparation"
  | "of Prestidigitation"
  | "of Propulsion"
  | "of Protection"
  | "of Provocation"
  | "of Puhuarte"
  | "of Puncturing"
  | "of Putrefaction"
  | "of Quashing"
  | "of Quelling"
  | "of Quenching"
  | "of Radiance"
  | "of Rage"
  | "of Raiding"
  | "of Rallying"
  | "of Reach"
  | "of Readiness"
  | "of Rebounding"
  | "of Rebuttal"
  | "of Recovery"
  | "of Recuperation"
  | "of Redemption"
  | "of Redirection"
  | "of Refilling"
  | "of Refuge"
  | "of Regrowth"
  | "of Regularity"
  | "of Reinforcement"
  | "of Rejuvenation"
  | "of Relentlessness"
  | "of Relishing"
  | "of Rending"
  | "of Renewal"
  | "of Renown"
  | "of Repairing"
  | "of Replenishing"
  | "of Resilience"
  | "of Resistance"
  | "of Resolve"
  | "of Restocking"
  | "of Restoration"
  | "of Restraint"
  | "of Resurgence"
  | "of Retaliation"
  | "of Reveling"
  | "of Revitalization"
  | "of Revival"
  | "of Revoking"
  | "of Righteousness"
  | "of Riker"
  | "of Riker's Veil"
  | "of Rime"
  | "of Rot"
  | "of Ruin"
  | "of Runeblazing"
  | "of Runeflaring"
  | "of Runegleaming"
  | "of Runes"
  | "of Runeshining"
  | "of Rupturing"
  | "of Ryslatha"
  | "of Sanctuary"
  | "of Saqawal"
  | "of Savouring"
  | "of Sealing"
  | "of Second Wind"
  | "of Seeping"
  | "of Shaping"
  | "of Shelter"
  | "of Shining"
  | "of Shocking"
  | "of Shockproofing"
  | "of Sin"
  | "of Siphoning"
  | "of Sipping"
  | "of Skill"
  | "of Slamming"
  | "of Sleet"
  | "of Snow"
  | "of Snuffing"
  | "of Soaring"
  | "of Sortilege"
  | "of Sparks"
  | "of Spellcraft"
  | "of Spilling"
  | "of Spirit"
  | "of Splintering"
  | "of Stabilisation"
  | "of Stability"
  | "of Staggering"
  | "of Static"
  | "of Staunching"
  | "of Steadiness"
  | "of Steel Skin"
  | "of Stemming"
  | "of Stiffness"
  | "of Stifling"
  | "of Stinging"
  | "of Stitching"
  | "of Stoicism"
  | "of Stone Skin"
  | "of Strength"
  | "of Stunning"
  | "of Success"
  | "of Suggestion"
  | "of Surefootedness"
  | "of Suturing"
  | "of Tacati"
  | "of Talent"
  | "of Tapping"
  | "of Tasting"
  | "of Taunting"
  | "of Tenaciousness"
  | "of Thawing"
  | "of Thermodynamics"
  | "of Thick Skin"
  | "of Tolerance"
  | "of Tooth Moss"
  | "of Torment"
  | "of Toxins"
  | "of Training"
  | "of Transformation"
  | "of Tree Moss"
  | "of Triumph"
  | "of Tul"
  | "of Turf Moss"
  | "of Tutelage"
  | "of Tzteosh"
  | "of Ultimatum"
  | "of Unholy Might"
  | "of Unmaking"
  | "of Unwavering"
  | "of Utilisation"
  | "of Uul-Netol"
  | "of Vampirism"
  | "of Variegation"
  | "of Venom"
  | "of Vibrance"
  | "of Victory"
  | "of Vigour"
  | "of Virulence"
  | "of Vitality"
  | "of Vivaciousness"
  | "of Vivification"
  | "of Voltage"
  | "of Walling"
  | "of Waning"
  | "of Warding"
  | "of Warmblood"
  | "of Warming"
  | "of Wasting"
  | "of Weaponcraft"
  | "of Weight"
  | "of Wildfire"
  | "of Will"
  | "of Wounding"
  | "of Wreaking"
  | "of Xoph"
  | "of Youth"
  | "of Youthfulness"
  | "of Zapping"
  | "of Zeal"
  | "of Zealousness"
  | "of Zest"
  | "of the Abalone"
  | "of the Acolyte"
  | "of the Administrator"
  | "of the Albatross"
  | "of the Antelope"
  | "of the Antidote"
  | "of the Antitoxin"
  | "of the Apocalypse"
  | "of the Apt"
  | "of the Arcanist"
  | "of the Ardent"
  | "of the Armadillo"
  | "of the Ashcloud"
  | "of the Assassin"
  | "of the Augur"
  | "of the Barricade"
  | "of the Barrier"
  | "of the Bastion"
  | "of the Bear"
  | "of the Beast"
  | "of the Beluga"
  | "of the Bleak"
  | "of the Blur"
  | "of the Boreal"
  | "of the Boxer"
  | "of the Brawler"
  | "of the Brute"
  | "of the Bulwark"
  | "of the Bushfire"
  | "of the Buttress"
  | "of the Carp"
  | "of the Cat"
  | "of the Catfish"
  | "of the Cheetah"
  | "of the Chimaera"
  | "of the Citadel"
  | "of the Cloud"
  | "of the Clouds"
  | "of the Combatant"
  | "of the Comet"
  | "of the Conger"
  | "of the Conjurer"
  | "of the Conquest"
  | "of the Conservator"
  | "of the Cormorant"
  | "of the Crow"
  | "of the Crusade"
  | "of the Crystal"
  | "of the Cure"
  | "of the Curlew"
  | "of the Deadeye"
  | "of the Deathless"
  | "of the Deer"
  | "of the Despot"
  | "of the Dielectric"
  | "of the Dove"
  | "of the Dragon"
  | "of the Drake"
  | "of the Eagle"
  | "of the Earnest"
  | "of the Eel"
  | "of the Elder"
  | "of the Elements"
  | "of the Elevated Conquest"
  | "of the Elevated Crusade"
  | "of the Elevated Elder"
  | "of the Elevated Hunt"
  | "of the Essence"
  | "of the Falcon"
  | "of the Fanatical"
  | "of the Fervid"
  | "of the Flatworm"
  | "of the Fox"
  | "of the Furnace"
  | "of the Galaxy"
  | "of the Gale"
  | "of the Gazelle"
  | "of the Gelid"
  | "of the Genius"
  | "of the Glacier"
  | "of the Gladiator"
  | "of the Gods"
  | "of the Godslayer"
  | "of the Goldfish"
  | "of the Goliath"
  | "of the Gorilla"
  | "of the Guardian"
  | "of the Guppy"
  | "of the Hare"
  | "of the Hearth"
  | "of the Heavens"
  | "of the Hedgehog"
  | "of the Heron"
  | "of the Horsefly"
  | "of the Hummingbird"
  | "of the Hunt"
  | "of the Hydra"
  | "of the Hyperboreal"
  | "of the Ibex"
  | "of the Ice"
  | "of the Iguana"
  | "of the Impala"
  | "of the Inclement"
  | "of the Inferno"
  | "of the Infinite"
  | "of the Initiate"
  | "of the Inquisitor"
  | "of the Inuit"
  | "of the Jaguar"
  | "of the Kakapo"
  | "of the Kaleidoscope"
  | "of the Keeper"
  | "of the Kiln"
  | "of the Leopard"
  | "of the Leviathan"
  | "of the Lightning"
  | "of the Lightning Rod"
  | "of the Lion"
  | "of the Lizard"
  | "of the Lost"
  | "of the Lynx"
  | "of the Maelstrom"
  | "of the Mage"
  | "of the Magma"
  | "of the Mammoth"
  | "of the Marksman"
  | "of the Meteor"
  | "of the Mockingbird"
  | "of the Molten Core"
  | "of the Mongoose"
  | "of the Monkey"
  | "of the Moray"
  | "of the Multiverse"
  | "of the Mussel"
  | "of the Narwhal"
  | "of the Necromancer"
  | "of the Newt"
  | "of the Novice"
  | "of the Opossum"
  | "of the Orca"
  | "of the Order"
  | "of the Overseer"
  | "of the Owl"
  | "of the Pangolin"
  | "of the Panther"
  | "of the Penguin"
  | "of the Petrel"
  | "of the Phantom"
  | "of the Philosopher"
  | "of the Phoenix"
  | "of the Plover"
  | "of the Polar Bear"
  | "of the Polymath"
  | "of the Prism"
  | "of the Prodigy"
  | "of the Protector"
  | "of the Pugilist"
  | "of the Pupil"
  | "of the Rabbit"
  | "of the Raccoon"
  | "of the Raider"
  | "of the Rainbow"
  | "of the Ranger"
  | "of the Rector"
  | "of the Remedy"
  | "of the Sable"
  | "of the Saboteur"
  | "of the Sage"
  | "of the Salamander"
  | "of the Sanctum"
  | "of the Sanderling"
  | "of the Sandpiper"
  | "of the Savant"
  | "of the Sea Lion"
  | "of the Seal"
  | "of the Sempiternal"
  | "of the Sentinel"
  | "of the Sentry"
  | "of the Skink"
  | "of the Skunk"
  | "of the Sky"
  | "of the Slavedriver"
  | "of the Slayer"
  | "of the Sniper"
  | "of the Solar Storm"
  | "of the Sorcerer"
  | "of the Span"
  | "of the Squall"
  | "of the Stalwart"
  | "of the Starfish"
  | "of the Storm"
  | "of the Student"
  | "of the Summoner"
  | "of the Sunfish"
  | "of the Taskmaster"
  | "of the Tempest"
  | "of the Thunderhead"
  | "of the Thundersnow"
  | "of the Titan"
  | "of the Tortoise"
  | "of the Tourniquet"
  | "of the Troll"
  | "of the Tundra"
  | "of the Underground"
  | "of the Universe"
  | "of the Urchin"
  | "of the Vandal"
  | "of the Veil"
  | "of the Virtuoso"
  | "of the Volcano"
  | "of the Wall"
  | "of the Walrus"
  | "of the Watchman"
  | "of the Whelpling"
  | "of the Wind"
  | "of the Worthy"
  | "of the Wrestler"
  | "of the Yeti"
  | "of the Zealous"
  | "of the Zephyr"
